/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksCreateRouteImport } from './routes/tasks.create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as TasksTaskIdIndexRouteImport } from './routes/tasks.$taskId.index'
import { Route as TasksTaskIdEditRouteImport } from './routes/tasks.$taskId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdIndexRoute = TasksTaskIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdEditRoute = TasksTaskIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TasksTaskIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/create': typeof TasksCreateRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/create': typeof TasksCreateRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/create': typeof TasksCreateRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/create' | '/tasks/$taskId/edit' | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksTaskIdRoute: typeof TasksTaskIdRouteWithChildren
  TasksCreateRoute: typeof TasksCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/': {
      id: '/tasks/$taskId/'
      path: '/'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof TasksTaskIdIndexRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    '/tasks/$taskId/edit': {
      id: '/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof TasksTaskIdEditRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
  }
}

interface TasksTaskIdRouteChildren {
  TasksTaskIdEditRoute: typeof TasksTaskIdEditRoute
  TasksTaskIdIndexRoute: typeof TasksTaskIdIndexRoute
}

const TasksTaskIdRouteChildren: TasksTaskIdRouteChildren = {
  TasksTaskIdEditRoute: TasksTaskIdEditRoute,
  TasksTaskIdIndexRoute: TasksTaskIdIndexRoute,
}

const TasksTaskIdRouteWithChildren = TasksTaskIdRoute._addFileChildren(
  TasksTaskIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksTaskIdRoute: TasksTaskIdRouteWithChildren,
  TasksCreateRoute: TasksCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
